name: cryptoview
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  talker_flutter: ^4.6.14
  talker_dio_logger: ^4.6.14
  talker_bloc_logger: ^4.6.14
  firebase_core: ^3.12.1
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  auto_route: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 6.9.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0



flutter:

  uses-material-design: true